### ISSUE TITLE
Image Links broken in README

### ISSUE THREAD

**Issue by robbawebba** [atom/autocomplete-emojis#17]
Just letting you know that the image links used in the README appear to be broken. The same problem occurs in the browser and in the settings page for this Atom package.
#### Browser (IE Edge):
<img width="737" alt="no-images-web" src="https://cloud.githubusercontent.com/assets/10067384/24718564/700e2e24-1a04-11e7-99d0-612a99c8ee5f.PNG">

#### Atom:
<img width="552" alt="no-images-atom" src="https://cloud.githubusercontent.com/assets/10067384/24718566/728a94ee-1a04-11e7-9d7f-5d6b2374fd65.PNG">

**Comment by rsese** [comment]
Thanks for the report @robbawebba, opening a quick PR now :v:

**Comment by eqot** [comment]
Hi @robbawebba,

Thank you very much for pointing it out.
Those images are located in DropBox but recently invisible due to DropBox's change.

I have copied all images from DropBox to this repository and update all URLs.

**Comment by robbawebba** [comment]
Sweet, thanks @eqot! Also, just a heads up, @rsese's PR #18 is still open and made the same changes as you so that may cause a merge conflict.

**Comment by rsese** [comment]
Oh great, thanks @eqot :bow:!  Also thanks for moving the images URLs off of DropBox.

I can just close my PR since you fixed the images and we can open a new one for any other small updates we wanted to make (e.g. the capitalization, @ben3eee's suggestion about just talking about the Settings in text rather than an image, etc.).
